Repository the-bugs/medcheck-web, pull requests merged in 2023-11, with the labels that each got.

#27 feat: Adiciona protótipo de formulário de cadastro e melhorias
  src/assets/imgs/aleatoria1.jpg
  src/assets/imgs/form_img.jpg
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/RegisterForm.tsx
  src/components/UserRegisterForm.tsx
  src/components/ui/ButtonComponent.tsx
  src/pages/Home.tsx
  src/pages/SignUp.tsx
  tailwind.config.js
Labels: front end PR

#29 feat: add Paciente signup
  src/components/UserRegisterForm.tsx
  src/pages/SignUp.tsx
Labels: front end PR

#41 refact: tipografia e cores padrão
  src/index.css
  tailwind.config.js
Labels: front end PR

#47 refact: Atualiza Hero Section para novo padrão e modulariza Home Page
  src/components/HeroSection.tsx
  src/pages/Home.tsx
Labels: front end PR, feature, refactor

#46 refact: Atualiza barra de navegação para novo padrão e corrige bug de index
  src/assets/imgs/MEDICALCHECKLOGO.svg
  src/components/Header.tsx
  src/components/ui/ButtonComponent.tsx
Labels: correcao, front end PR, refactor

#45 Button component
  src/components/ui/ButtonComponent.tsx
  src/index.css
  tailwind.config.js
Labels: front end PR, refactor

#55 fix: Atualiza Hero Section para padrão Figma e corrige bug de navbar
  src/components/Header.tsx
  src/components/HeroSection.tsx
Labels: correcao, front end PR

#57 feat: Adiciona context para transitar dados de usuário logado
  .env.example
  src/App.tsx
  src/contexts/AuthContext.tsx
  src/contexts/index.tsx
Labels: front end PR, feature

#63 Authentication
  .gitignore
  src/assets/imgs/loginIMG.png
  src/components/UserRegisterForm.tsx
  src/contexts/AuthContext.tsx
  src/pages/Login.tsx
  src/pages/SignUp.tsx
Labels: bug, correcao, front end PR

#64 Fix toast
  src/App.tsx
Labels: correcao, front end PR

#66 fix: Atualiza context para guardar mais dados
  src/contexts/AuthContext.tsx
  src/pages/Login.tsx
Labels: correcao, front end PR

#69 Fix login
  src/contexts/AuthContext.tsx
  src/pages/Login.tsx
Labels: correcao, front end PR

#71 Fix login again
  package.json
  src/App.tsx
  src/components/UserRegisterForm.tsx
  src/contexts/AuthContext.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
Labels: correcao, front end PR, feature

#72 Wip doc search
  src/assets/imgs/desktop_DoctorSearch.png
  src/assets/imgs/mobile_DoctorSearch.png
  src/components/DoctorSearch.tsx
  src/components/ui/StyledInput.tsx
  src/pages/Home.tsx
Labels: front end, feature

#78 Doctors found
  src/App.tsx
  src/components/DoctorSearch.tsx
  src/contexts/AuthContext.tsx
  src/pages/DoctorFound.tsx
  src/pages/UiComponents.tsx
  src/utils/UseSpecialties.tsx
Labels: correcao, front end PR, feature

#84 Feat/requisitos finalizados
  package.json
  src/App.tsx
  src/components/AddSpecialtyModal.tsx
  src/components/AdminMenus.tsx
  src/components/Header.tsx
  src/components/ShowAgenda.tsx
  src/components/ShowAgendaAndMakeAppointment.tsx
  src/components/SpecialtiesMenuLink.tsx
  src/components/ui/StyledInput.tsx
  src/contexts/AuthContext.tsx
  src/pages/DoctorFound.tsx
  src/pages/Home.tsx
  src/pages/SpecialtiesMenuPage.tsx
  src/pages/UiComponents.tsx
Labels: correcao, front end PR, feature
